**SOAL NO 1 (Matrix Tensors)**

In [3]:
import numpy as np

buat matrix X berukuran 2x3 menggunakan numpy

In [7]:
X = np.array([[15, 7, 20], [10, 6, 4]])
print(X)

[[15  7 20]
 [10  6  4]]


tampilkan ukuran dari matrix X

In [9]:
print(X.shape)

(2, 3)


tampilkan seluruh elemen dari kolom pertama dari matrix X

In [10]:
print(X[:,0])

[15 10]


tampilkan seluruh elemen dari baris kedua dari matrix X

In [12]:
print(X[1,:])

[10  6  4]


**SOAL NO 2 (Matrix Tensors) (PyTorch)**

ulangi soal nomor 1 menggunakan pytorch

In [18]:
import torch

X_pt = torch.tensor([[15, 7, 20], [10, 6, 4]])
print(X_pt)
print()

print(X_pt.shape)
print()

print(X_pt[:,0])
print()

print(X_pt[1,:])

tensor([[15,  7, 20],
        [10,  6,  4]])

torch.Size([2, 3])

tensor([15, 10])

tensor([10,  6,  4])


ulangi soal nomor 1 menggunakan tensorflow

In [23]:
import tensorflow as tf

X_tf = tf.Variable([[15, 7, 20], [10, 6, 4]])
print(X_tf)
print()

print(tf.shape(X_tf))
print()

print(X_tf[:,0])
print()

print(X_tf[1,:])

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[15,  7, 20],
       [10,  6,  4]], dtype=int32)>

tf.Tensor([2 3], shape=(2,), dtype=int32)

tf.Tensor([15 10], shape=(2,), dtype=int32)

tf.Tensor([10  6  4], shape=(3,), dtype=int32)
