**SOAL NO 1 (VECTORS AND VECTOR TRANSPOSITION)**

buat vector x dengan ukuran 3x1

In [1]:
import numpy as np

x = np.array([[10],
              [15],
              [20]])
print(x)

[[10]
 [15]
 [20]]


hitung panjang vector x

In [7]:
print(f'Panjang vector x: {len(x)}')

Panjang vector x: 3


tampilkan ukuran vector x

In [8]:
print(f'Ukuran dari vector x: {x.shape}')

Ukuran dari vector x: (3, 1)


tampilkan tipe data dari vector x

In [12]:
print(f'Tipe dari vector x: {type(x)}')

Tipe dari vector x: <class 'numpy.ndarray'>


akses elemen pertama dari vector x

In [13]:
print(f'Elemen pertama dari vector x: {x[0]}')

Elemen pertama dari vector x: [10]


tampilkan tipe data elemen pertama dari vector x

In [14]:
print(f'Tipe data elemen pertama vector x: {type(x[0])}')

Tipe data elemen pertama vector x: <class 'numpy.ndarray'>


**SOAL NO 2 (VECTORS AND VECTOR TRANSPOSITION)**

lakukan transpose pada vector x dan simpan pada variabel x_t

In [16]:
x_trans = x.transpose()
print('Transpose dari vector x adalah:')
print(x_trans)

Transpose dari vector x adalah:
[[10 15 20]]


tampilkan ukuran dari vector x_t

In [17]:
print('Ukuran dari vector x_t:')
print(x_trans.shape)

Ukuran dari vector x_t:
(1, 3)


lakukan transpose pada vector y dan simpan pada variabel y_t

In [18]:
y = np.array([[10],
              [15],
              [20]])
print(y)

[[10]
 [15]
 [20]]


tampilkan ukuran dari vector x_t

In [19]:
print(f'Ukuran dari vector y: {y.shape}')

Ukuran dari vector y: (3, 1)


**SOAL NO 3 (VECTORS AND VECTOR TRANSPOSITION) (TENSORFLOW)**

lakukan soal nomor 2 menggunakan pytorch dan tensorflow

In [20]:
import tensorflow as tf

x_tf = tf.Variable([[10],
                    [15],
                    [20]])
print(x_tf)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[10],
       [15],
       [20]], dtype=int32)>


In [21]:
print(x_tf.shape)

(3, 1)


In [22]:
y_tf = tf.Variable([[10],
                    [15],
                    [20]])
print(y_tf)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[10],
       [15],
       [20]], dtype=int32)>


In [24]:
print(y_tf.shape)

(3, 1)


**SOAL NO 3 (VECTORS AND VECTOR TRANSPOSITION) (PYTORCH)**

lakukan soal nomor 2 menggunakan pytorch dan tensorflow

In [25]:
import torch

x_pt = torch.tensor([[10],
                    [15],
                    [20]])
print(x_pt)

tensor([[10],
        [15],
        [20]])


In [26]:
print(x_pt.shape)

torch.Size([3, 1])


In [27]:
y_pt = torch.tensor([[10],
                    [15],
                    [20]])
print(y_pt)

tensor([[10],
        [15],
        [20]])


In [28]:
print(y_pt.shape)

torch.Size([3, 1])
