In [1]:
import numpy as np
import torch
import tensorflow as tf

SOAL NO 1 (BASIC TENSOR ARITHMETIC (THE HADAMARD PRODUCT))

In [2]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
print("Matrix X dengan ukuran 2x3 menggunakan numpy:")
X = np.array(([5, 15, 25], [35, 45, 55]))
print(X)

Matrix X dengan ukuran 2x3 menggunakan numpy:
[[ 5 15 25]
 [35 45 55]]


In [3]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor(([5, 15, 25], [35, 45, 55]))
print("Matrix X_pt dengan ukuran 2x3 menggunakan pytorch:")
print(X_pt)

Matrix X_pt dengan ukuran 2x3 menggunakan pytorch:
tensor([[ 5, 15, 25],
        [35, 45, 55]])


In [4]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable(([5, 15, 25], [35, 45, 55]))
print("Matrix dengan ukuran 2x3 menggunakan tensorflow:")
print(X_tf)

Matrix dengan ukuran 2x3 menggunakan tensorflow:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 5, 15, 25],
       [35, 45, 55]], dtype=int32)>


lakukan perkalian matrix X, X_pt, X_tf dengan suatu skalar

In [5]:
# Perkalian X dengan suatu skalar
print("Hasil perkalian X dengan suatu skalar:")
print(X * 2)

Hasil perkalian X dengan suatu skalar:
[[ 10  30  50]
 [ 70  90 110]]


In [6]:
# Perkalian X_pt dengan suatu skalar
print("Hasil perkalian X_pt dengan suatu skalar:")
print(torch.mul(X_pt, 2))

Hasil perkalian X_pt dengan suatu skalar:
tensor([[ 10,  30,  50],
        [ 70,  90, 110]])


In [7]:
# Perkalian X_tf dengan suatu skalar
print("Hasil perkalian X_tf dengan suatu skalar:")
print(tf.multiply(X_tf, 2))

Hasil perkalian X_tf dengan suatu skalar:
tf.Tensor(
[[ 10  30  50]
 [ 70  90 110]], shape=(2, 3), dtype=int32)


lakukan penjumlahan matrix X, X_pt, X_tf dengan suatu skalar

In [8]:
# Penjumlahan X dengan suatu skalar
print("Hasil penjumlahan X dengan suatu skalar:")
print(X + 2)

Hasil penjumlahan X dengan suatu skalar:
[[ 7 17 27]
 [37 47 57]]


In [9]:
# Penjumlahan X_pt dengan suatu skalar
print("Hasil penjumlahan X_pt dengan suatu skalar:")
print(torch.add(X_pt, 2))

Hasil penjumlahan X_pt dengan suatu skalar:
tensor([[ 7, 17, 27],
        [37, 47, 57]])


In [10]:
# Penjumlahan X_tf dengan suatu skalar
print("Hasil penjumlahan X_tf dengan suatu skalar:")
print(tf.add(X_tf, 2))

Hasil penjumlahan X_tf dengan suatu skalar:
tf.Tensor(
[[ 7 17 27]
 [37 47 57]], shape=(2, 3), dtype=int32)


lakukan pengurangan matrix X, X_pt, X_tf dengan suatu skalar

In [11]:
# Pengurangan X dengan suatu skalar
print("Hasil pengurangan X dengan suatu skalar:")
print(X - 2)

Hasil pengurangan X dengan suatu skalar:
[[ 3 13 23]
 [33 43 53]]


In [12]:
# Pengurangan X_pt dengan suatu skalar
print("Hasil pengurangan X_pt dengan suatu skalar:")
print(torch.sub(X_pt, 2))

Hasil pengurangan X_pt dengan suatu skalar:
tensor([[ 3, 13, 23],
        [33, 43, 53]])


In [13]:
# Pengurangan X_tf dengan suatu skalar
print("Hasil pengurangan X_tf dengan suatu skalar:")
print(tf.subtract(X_tf, 2))

Hasil pengurangan X_tf dengan suatu skalar:
tf.Tensor(
[[ 3 13 23]
 [33 43 53]], shape=(2, 3), dtype=int32)


SOAL NO 2 (BASIC TENSOR ARITHMETIC (THE HADAMARD PRODUCT))

In [14]:
# buat matrix Y dengan ukuran 2x3 menggunakan numpy
Y = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix Y dengan ukuran 2x3 menggunakan numpy:")
print(Y)

Matrix Y dengan ukuran 2x3 menggunakan numpy:
[[1 2 3]
 [4 5 6]]


In [15]:
# buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
Y_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Matrix Y_pt dengan ukuran 2x3 menggunakan numpy:")
print(Y_pt)

Matrix Y_pt dengan ukuran 2x3 menggunakan numpy:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [16]:
# buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow
Y_tf = tf.Variable([[1, 2, 3], [4, 5, 6]])
print("Matrix Y_tf dengan ukuran 2x3 menggunakan numpy:")
print(Y_tf)

Matrix Y_tf dengan ukuran 2x3 menggunakan numpy:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [17]:
# kalikan X dengan Y
print("Hasil perkalian X dengan Y:")
print(X * Y)

Hasil perkalian X dengan Y:
[[  5  30  75]
 [140 225 330]]


In [18]:
# kalikan X dengan Y
print("Hasil perkalian X dengan Y:")
print(X * Y)

Hasil perkalian X dengan Y:
[[  5  30  75]
 [140 225 330]]


In [19]:
# kalikan X_pt dengan Y_pt
print("Hasil perkalian X_pt dengan Y_pt:")
print(torch.mul(X_pt, Y_pt))

Hasil perkalian X_pt dengan Y_pt:
tensor([[  5,  30,  75],
        [140, 225, 330]])


In [20]:
# kalikan X_tf dengan Y_tf
print("Hasil perkalian X_tf dengan Y_tf:")
print(tf.multiply(X_tf, Y_tf))

Hasil perkalian X_tf dengan Y_tf:
tf.Tensor(
[[  5  30  75]
 [140 225 330]], shape=(2, 3), dtype=int32)
