**SOAL NO 1 (TENSOR REDUCTION)**

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array(([2, 12, 22], [32, 42, 52]))
print("Matrix X dengan ukuran 2x3 menggunakan numpy:")
print(X)

Matrix X dengan ukuran 2x3 menggunakan numpy:
[[ 2 12 22]
 [32 42 52]]


In [3]:
X.sum()

np.int64(162)

In [4]:
# matrix X_pt ukuran 2x3 pytorch
X_pt = torch.tensor(([2, 12, 22], [32, 42, 52]))
print("Matrix X_pt dengan ukuran 2x3 menggunakan pytorch:")
print(X_pt)

Matrix X_pt dengan ukuran 2x3 menggunakan pytorch:
tensor([[ 2, 12, 22],
        [32, 42, 52]])


In [6]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable(([2, 12, 22], [32, 42, 52]))
print("Matrix X_tf dengan ukuran 2x3 menggunakan tensorflow:")
print(X_tf)

Matrix X_tf dengan ukuran 2x3 menggunakan tensorflow:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2, 12, 22],
       [32, 42, 52]], dtype=int32)>


**SOAL NO 2 (TENSOR REDUCTION)**

In [7]:
# hitung hasil penjumlahan seluruh elemen matrix X
print("Hasil penjumlahan seluruh elemen matrix X:")
print(X.sum())

Hasil penjumlahan seluruh elemen matrix X:
162


In [8]:
# hitung hasil penjumlahan seluruh elemen matrix X_pt
print("Hasil penjumlahan seluruh elemen matrix X_pt:")
print(torch.sum(X_pt))

Hasil penjumlahan seluruh elemen matrix X_pt:
tensor(162)


In [9]:
# hitung hasil penjumalahn seluruh elemen matrix X_tf
print("Hasil penjumlahan seluruh elemen matrix X_tf:")
print(tf.reduce_sum(X_tf))

Hasil penjumlahan seluruh elemen matrix X_tf:
tf.Tensor(162, shape=(), dtype=int32)


**SOAL NO 3 (TENSOR REDUCTION)**

In [10]:
# hitung hasil penjumlahan matrix X berdasarkan row nya
print("Hasil penjumlahan matrix X berdasarkan row nya:")
print(X.sum(axis=1))

Hasil penjumlahan matrix X berdasarkan row nya:
[ 36 126]


In [11]:
# hitung hasil penjumlahan matrix X_pt berdasarkan row nya
print("Hasil penjumlahan matrix X_pt berdasarkan row nya:")
print(torch.sum(X_pt, 1))

Hasil penjumlahan matrix X_pt berdasarkan row nya:
tensor([ 36, 126])


In [12]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya
print("Hasil penjumlahan matrix X_tf berdasarkan row nya:")
print(tf.reduce_sum(X_tf, 1))

Hasil penjumlahan matrix X_tf berdasarkan row nya:
tf.Tensor([ 36 126], shape=(2,), dtype=int32)


**SOAL NO 4 (TENSOR REDUCTION)**

In [13]:
# hitung hasil penjumlahan matrix X berdasarkan kolom nya
print("Hasil penjumlahan matrix X berdasarkan kolom nya:")
print(X.sum(axis=0))

Hasil penjumlahan matrix X berdasarkan kolom nya:
[34 54 74]


In [14]:
# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
print("Hasil penjumlahan matrix X_pt berdasarkan kolom nya:")
print(torch.sum(X_pt, 0))

Hasil penjumlahan matrix X_pt berdasarkan kolom nya:
tensor([34, 54, 74])


In [15]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya
print("Hasil penjumlahan matrix X_tf berdasarkan row nya:")
print(tf.reduce_sum(X_tf, 0))

Hasil penjumlahan matrix X_tf berdasarkan row nya:
tf.Tensor([34 54 74], shape=(3,), dtype=int32)


**SOAL NO 5 (TENSOR REDUCTION)**

hitung nilai minimal dari matrix X, X_pt dan X_tf

In [16]:
# nilai maksimal dari matrix X
print(X.min())

2


In [17]:
# nilai maksimal dari matrix X_pt
print(torch.min(X_pt))

tensor(2)


In [18]:
# nilai maksimal dari matrix X_tf
print(tf.reduce_min(X_tf))

tf.Tensor(2, shape=(), dtype=int32)


hitung nilai maksimal dari matrix X, X_pt dan X_tf

In [19]:
# nilai maksimal dari matrix X
print(X.max())

52


In [20]:
# nilai maksimal dari matrix X_pt
print(torch.max(X_pt))

tensor(52)


In [21]:
# nilai maksimal dari matrix X_tf
print(tf.reduce_max(X_tf))

tf.Tensor(52, shape=(), dtype=int32)


hitung nilai rata-rata dari matrix X, X_pt dan X_tf

In [23]:
# nilai rata-rata dari matrix X
print(X.mean())

27.0


In [22]:
# nilai rata-rata dari matrix X_pt
X_pt = X_pt.float()
print(torch.mean(X_pt))

tensor(27.)


In [24]:
# nilai rata-rata dari matrix X_tf
print(tf.reduce_mean(X_tf))

tf.Tensor(27, shape=(), dtype=int32)


**SOAL NO 6 (TENSOR REDUCTION)**

In [25]:
# hitung hasil perkalian seluruh elemen matrix X
print(X.prod())

36900864


In [26]:
# hitung hasil perkalian seluruh elemen matrix X_pt
X_pt = X_pt.int()
print(torch.prod(X_pt))

tensor(36900864)


In [27]:
# hitung hasil perkalian seluruh elemen matrix X_tf
print(tf.reduce_prod(X_tf))

tf.Tensor(36900864, shape=(), dtype=int32)
