In [1]:

import numpy as np
import torch
import tensorflow as tf

print("SOAL NO 1 (TENSOR TRANSPOSITION)")

SOAL NO 1 (TENSOR TRANSPOSITION)


In [2]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[10, 20, 30], [40, 50, 60]])
print("Matrix X dengan ukuran 2x3:")
print(X)

Matrix X dengan ukuran 2x3:
[[10 20 30]
 [40 50 60]]


In [3]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[10, 20, 30], [40, 50, 60]])
print("Matrix X_pt dengan ukuran 2x3:")
print(X_pt)

Matrix X_pt dengan ukuran 2x3:
tensor([[10, 20, 30],
        [40, 50, 60]])


In [4]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[10, 20, 30], [40, 50, 60]])
print("Matrix X_tf dengan ukuran 2x3:")
print(X_tf)

Matrix X_tf dengan ukuran 2x3:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>


In [5]:
print("SOAL NO 2 (TENSOR TRANSPOSITION)")

SOAL NO 2 (TENSOR TRANSPOSITION)


In [6]:
# lakukan transpose pada matrix X, X_pt, X_tf
print("Transpose dari X:")
print(X.T)
print()

print("Transpose dari X_pt:")
print(X_pt.T)
print()

print("Transpose dari X_tf:")
print(tf.transpose(X_tf))

Transpose dari X:
[[10 40]
 [20 50]
 [30 60]]

Transpose dari X_pt:
tensor([[10, 40],
        [20, 50],
        [30, 60]])

Transpose dari X_tf:
tf.Tensor(
[[10 40]
 [20 50]
 [30 60]], shape=(3, 2), dtype=int32)
