**SOAL NO 1 (THE DOT PRODUCT)**

In [17]:
import numpy as np
import torch
import tensorflow as tf

buat vector x dan y dengan ukuran 1x3 menggunakan numpy

In [18]:
x = np.array([5, 15, 25])
y = np.array([10, 20, 30])
print("Vector x dengan ukuran 1x3:")
print(x)
print()

print("Vector y dengan ukuran 1x3:")
print(y)

Vector x dengan ukuran 1x3:
[ 5 15 25]

Vector y dengan ukuran 1x3:
[10 20 30]


buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch

In [19]:
x_pt = torch.tensor([5, 15, 25])
y_pt = torch.tensor([10, 20, 30])
print("Vector x_pt dengan ukuran 1x3:")
print(x_pt)
print()

print("Vector y_pt dengan ukuran 1x3:")
print(y_pt)

Vector x_pt dengan ukuran 1x3:
tensor([ 5, 15, 25])

Vector y_pt dengan ukuran 1x3:
tensor([10, 20, 30])


buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow

In [20]:
x_tf = tf.Variable([5, 15, 25])
y_tf = tf.Variable([10, 20, 30])
print("Vector x_tf dengan ukuran 1x3:")
print(x_tf)
print()

print("Vector y_tf dengan ukuran 1x3:")
print(y_tf)

Vector x_tf dengan ukuran 1x3:
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 5, 15, 25], dtype=int32)>

Vector y_tf dengan ukuran 1x3:
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 30], dtype=int32)>


**SOAL NO 2 (THE DOT PRODUCT)**

hitung perkalian dot product antara vector x dan vector y

In [21]:
print("Hasil perkalian dot product antara vector x dan y:")
print(np.dot(x, y))

Hasil perkalian dot product antara vector x dan y:
1100


hitung perkalian dot product antara vector x_pt dan vector y_pt

In [22]:
print("Hasil perkalian dot product antara vector x_pt dan y_pt:")
print(torch.dot(x_pt, y_pt))

Hasil perkalian dot product antara vector x_pt dan y_pt:
tensor(1100)


hitung perkalian dot product antara vector x_tf dan vector y_tf

In [23]:
print("Hasil perkalian dot product antara x_tf dan y_tf:")
print(tf.reduce_sum(tf.multiply(x_tf, y_tf)))

Hasil perkalian dot product antara x_tf dan y_tf:
tf.Tensor(1100, shape=(), dtype=int32)


**SOAL NO 3 (THE DOT PRODUCT)**

![gambar soal no 3 THE DOT PRODUCT](<gambar soal.png>)

1. What is ***Y*** Transpose?

In [24]:
Y = np.array(([42, 4, 7, 99], [-99, -3, 17, 22]))
Y_tp = Y.transpose()
print("Transpose dari Y adalah:")
print(Y_tp)

Transpose dari Y adalah:
[[ 42 -99]
 [  4  -3]
 [  7  17]
 [ 99  22]]


2. What is the Hadamard product of these matrices?

In [25]:
X = np.array([[25, 10], [-2, 1]])
Y = np.array([[-1, 7], [10, 8]])
print("Hadamard product dari matriks tersebut adalah:")
print(X * Y)

Hadamard product dari matriks tersebut adalah:
[[-25  70]
 [-20   8]]


3. What is the dot product of the tensors ***w*** and ***x***?

In [26]:
w = np.array([-1, 2, -2])
x = np.array([5, 10, 0])
print("Dot product dari tensor w dan x adalah:")
print(np.dot(w, x))

Dot product dari tensor w dan x adalah:
15
