no1

In [1]:
import torch

In [6]:
M_e = torch.tensor([[0, 1, 5], [2, 4, 3], [8, 2, 1]])
M_e

tensor([[0, 1, 5],
        [2, 4, 3],
        [8, 2, 1]])

In [7]:
V_e = torch.tensor([[-2, 1, -3], [0, -1, 2]]).T
V_e

tensor([[-2,  0],
        [ 1, -1],
        [-3,  2]])

In [8]:
torch.matmul(M_e, V_e)

tensor([[-14,   9],
        [ -9,   2],
        [-17,   0]])