**SOAL NO 1 (MATRIX INVERSION)**

In [2]:
import numpy as np
import torch
import tensorflow as tf

buat matrix X ukuran 2x2 menggunakan numpy

In [3]:
X = np.array(([12, 20], [9, 30]))
print(X)

[[12 20]
 [ 9 30]]


buat invers dari matrix X dan beri nama Xinv menggunakan numpy

In [4]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 0.16666667, -0.11111111],
       [-0.05      ,  0.06666667]])

kalikan X dengan Xinv menggunakan numpy

In [6]:
np.dot(Xinv, X)

array([[ 1.00000000e+00, -1.11022302e-16],
       [-9.71445147e-17,  1.00000000e+00]])

**SOAL NO 2 (MATRIX INVERSION)**

selesaikan persamaan berikut menggunakan numpy, tensorflow dan pytorch

![soal](image.png)

**NUMPY**

In [7]:
X = np.array([[4, 2], [-5, -3]])
Y = np.array([[4], [-7]])
Z = np.linalg.solve(X, Y)
print(Z)

[[-1.]
 [ 4.]]


**TORCH**

In [13]:
X_pt = torch.tensor([[4, 2], [-5, -3]], dtype=float)
Y_pt = torch.tensor([[4], [-7]], dtype=float)
Z_pt = torch.linalg.solve(X_pt, Y_pt)
print(Z_pt)

tensor([[-1.0000],
        [ 4.0000]], dtype=torch.float64)


**TENSORFLOW**

In [16]:
X_tf = tf.Variable([[4, 2], [-5, -3]], dtype=tf.float64)
Y_tf = tf.Variable([[4], [-7]], dtype=tf.float64)
Z_tf = tf.linalg.solve(X_tf, Y_tf)
print(Z_tf)

tf.Tensor(
[[-1.]
 [ 4.]], shape=(2, 1), dtype=float64)
