matrixmultiplication

no 1

numpy

In [3]:
import numpy as np

In [4]:
#membuat matrix 2x3 menggunakan numpy
A = np.array([[5, 2, 1], [6, 4, 2]])
A

array([[5, 2, 1],
       [6, 4, 2]])

In [6]:
#membuat vektor 3x1 menggunakan numpy
b = np.array([4, 1, 2])
b

array([4, 1, 2])

pytorch

In [7]:
import torch

In [8]:
#membuat matrix 2x3 menggunakan torch
A_pt = torch.tensor([[5, 2, 1], [6, 4, 2]])
A_pt

tensor([[5, 2, 1],
        [6, 4, 2]])

In [9]:
#membuat vektor 3x1 menggunakan torch
b_pt = torch.tensor([4, 1, 2])
b_pt

tensor([4, 1, 2])

tensorflow

In [10]:
import tensorflow as tf

In [12]:
#membuat matrix 2x3 menggunakan tensorflow
A_tf = tf.Variable([[5, 2, 1], [6, 4, 2]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[5, 2, 1],
       [6, 4, 2]], dtype=int32)>

In [13]:
#membuat vektor 3x1 menggunakan tensorflow
b_tf = tf.Variable([4, 1, 2])
b_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 1, 2], dtype=int32)>

no 2

In [14]:
#menampilkan ukuran matrix A
A.shape

(2, 3)

In [15]:
#menampilkan ukuran vektor b
b.shape

(3,)

no 3

In [16]:
#mengalikan matrix A dengan vektor b
np.dot(A, b)

array([24, 32])

In [17]:
#mengalikan matrix A_pt dengan vektor b_pt
torch.matmul(A_pt, b_pt)


tensor([24, 32])

In [18]:
#mengalikan matrix A_tf dengan vektor b_tf
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([24, 32], dtype=int32)>

no 4

In [19]:
#membuat matrix B 3x3 menggunakan numpy
B = np.array([[3, 4, 2], [2, 1, 7], [5, 2, 1]])
B

array([[3, 4, 2],
       [2, 1, 7],
       [5, 2, 1]])

In [20]:
#membuat matrix B 3x3 menggunakan pytorch
B_pt = torch.tensor([[3, 4, 2], [2, 1, 7], [5, 2, 1]])
B_pt

tensor([[3, 4, 2],
        [2, 1, 7],
        [5, 2, 1]])

In [21]:
#membuat matrix B 3x3 menggunakan tensorflow
B_tf = tf.Variable([[3, 4, 2], [2, 1, 7], [5, 2, 1]])
B_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[3, 4, 2],
       [2, 1, 7],
       [5, 2, 1]], dtype=int32)>

no 5

In [22]:
#mengalikan matrix A dengan matrix B
np.dot(A, B)

array([[24, 24, 25],
       [36, 32, 42]])

In [23]:
#mengalikan matrix A_pt dengan matrix B_pt
torch.matmul(A_pt, B_pt)

tensor([[24, 24, 25],
        [36, 32, 42]])

In [24]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[24, 24, 25],
       [36, 32, 42]], dtype=int32)>

no 6

membuktikan apakah perkalian AB=BA bersifat komutatif

In [25]:
np.dot(A, B)

array([[24, 24, 25],
       [36, 32, 42]])

In [26]:
np.dot(B, A)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)