no1

In [1]:
import numpy as np

In [ ]:
#membuat matrix simetris ukuran 3x3
X_sym = np.array([[3, 5, 6], [5, 3, 1], [6, 1, 8]])
X_sym

array([[3, 5, 6],
       [5, 3, 1],
       [6, 1, 8]])

In [ ]:
#mentransporskan matrix
X_sym.T

array([[3, 5, 6],
       [5, 3, 1],
       [6, 1, 8]])

In [ ]:
#membuktikan matrix simetris atau tidak
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

no2

In [5]:
import torch

In [ ]:
#membuat matrix identitas berukuran 4x4
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [12]:
#membuat vektor b_pt berukuran 4x1
b_pt = torch.tensor([[13], [12], [15], [14]])
b_pt

tensor([[13],
        [12],
        [15],
        [14]])

In [15]:
#mengalikan matrix I dengan vektor b_pt
torch.matmul(I, b_pt)

tensor([[13],
        [12],
        [15],
        [14]])